### ISSUE TITLE
Automatic Heroku deployment failed

### ISSUE THREAD

**Issue by creohn** [creohn/creBotter_twitter#1]
An automatic deployment for crebotter failed. The build failed with the message Unauthorized.

Token from user botter@creohn.de was used to interact with GitHub. This account was matched as the GitHub committer.

You can also check that the user who connected the app or pipeline to GitHub still has access to the app and to the Github repository.

In this case, reconnecting to GitHub will often fix the issue.

If you believe that this build failure was not due to an issue in your app, please open a support ticket at https://help.heroku.com.

**Comment by rbarner14** [comment]
I got the same.  Are there any resolutions?

**Comment by turron65** [comment]
Have the same problem, any solution?

**Comment by picheli20** [comment]
@Nintendero65pro looks like is a heroku issue: https://status.heroku.com/, so either deploy in a different way or wait them to re-activate it.


<img width="951" alt="Screen Shot 2022-04-17 at 7 35 54 PM" src="https://user-images.githubusercontent.com/3877606/163725950-3d1a8044-e600-44fc-831a-266a7c41e598.png">

**Comment by turron65** [comment]
> @Nintendero65pro looks like is a heroku issue: https://status.heroku.com/, so either deploy in a different way or wait them to re-activate it.
> 
> 
> <img width="951" alt="Screen Shot 2022-04-17 at 7 35 54 PM" src="https://user-images.githubusercontent.com/3877606/163725950-3d1a8044-e600-44fc-831a-266a7c41e598.png">
> 

Yeah, tyvm, readed it in heroku's status webpage, such a shame what is happening.
The impressive thing is... How did you answered so fast in this 1yo question???

**Comment by rohankeskar19** [comment]
> @Nintendero65pro looks like is a heroku issue: https://status.heroku.com/, so either deploy in a different way or wait them to re-activate it.
> 
> <img alt="Screen Shot 2022-04-17 at 7 35 54 PM" width="951" src="https://user-images.githubusercontent.com/3877606/163725950-3d1a8044-e600-44fc-831a-266a7c41e598.png">

How do you deploy in a different way

**Comment by picheli20** [comment]
@Nintendero65pro was the first google result about the issue 😄 

@rohankeskar19 via heroku cli https://devcenter.heroku.com/articles/git

**Comment by rohankeskar19** [comment]
> @Nintendero65pro was the first google result about the issue 😄
> 
> @rohankeskar19 via heroku cli https://devcenter.heroku.com/articles/git

Thanks

**Comment by Kaweees** [comment]
This also was the first result for me when I Googled the issue. Thanks for the clear explanation @picheli20 😄!

**Comment by William-McGonagle** [comment]
Salesforce is secretly convincing us to use Heroku CLI instead of Github. But don't worry, I will never.

**Comment by creohn** [comment]
Heroku was aquired by SalesForce &  the free Plan is terminated : (
